### ISSUE TITLE
if there are only 2-3 column how to fit on full screen

### ISSUE THREAD

**Issue by piyushSinghalDemo** [richardtallent/vue-scrolling-table#10]
Hi,

I have 3-4 columns only that time in table we do not need horizontal scroll, and these column should fit on full screen.can we give that kind of dynamic width.
right now it looks like ?
![grid](https://user-images.githubusercontent.com/30336741/52941136-2293e080-338e-11e9-94b4-1b42b669e4bd.png)

Here i have vertical scroll but columns are not on full screen

**Comment by richardtallent** [comment]
The component isn't designed to support dynamic-width columns, because dynamic widths are based on the idea that the table has a given width and must allocate that width to the columns. Here, the table is has overflow, so there is no "correct" table width. Also, because of the box model used to render the table elements, if you set the THEAD and TBODY children to have `width:auto`, they won't line up with one another (i.e., the "auto width" calculation for header and body elements are independent, not synchronized like they are in a normal table).

My recommendation is to create some classes based on the column type (checkbox, name, email, date, etc.) with some reasonable default widths. For variable-length text fields, you could also use a function to compute the appropriate width needed for the longest value in a given column, with a minimum and maximum value (basically simulating an "auto" width). If the total width exceeds the width of the component, the horizontal scroll feature will come into play automatically.
