### ISSUE TITLE
Table Rendering Weirdly

### ISSUE THREAD

**Issue by piperRyan** [richardtallent/vue-scrolling-table#11]
Link to [sandbox](https://codesandbox.io/s/1omxj68ozj). 

It probably due to how I am using it,but based upon the examples this is not the output I expected. Is there something I am missing?

**Comment by richardtallent** [comment]
You have 6 header columns and only 5 cells in the data row. Otherwise it seems on the surface to look correct. Can you explain in more detail what you're expecting?

**Comment by piperRyan** [comment]
> You have 6 header columns and only 5 cells in the data row.

Oops, sorry here is updated sandbox instance: https://codesandbox.io/s/5y60496opx

> Can you explain in more detail what you're expecting?

I think it was the combo of the tbody cells not aligning themselves correctly and some of the tbody cells having a different background colour than others. Obviously I can overwrite this with css,but that behaviour doesn't seem to be inline with the demo.

**Comment by piperRyan** [comment]
It seems this behaviour only occurs when there is one row in the table.

**Comment by richardtallent** [comment]
The TBODY cells with the different background color are because they are TH instead of TD, and the component has a default TH color that is a light grey. In the demo, all cells in the TBODY are TD elements, only the THEAD uses TH cells. 

If I'm understanding you correctly, the alignment issue is basically the same problem. HTML defines the default `text-align` value for TH elements as `center`, and the default for `TD` is left.

In the demo, I've included the Bulma CSS library, which resets the default CSS and applies its own default table styles, including left alignment and more relaxed cell padding.

Overall, this component does very little table styling--only what is needed to make the scrolling happen as reliably as possible, and also setting the default background colors for table, th, and td elements just so the component looks "ok" without any additional CSS. I could've included a lot more default CSS to make tables look prettier "out of the box," but then it would make it far more difficult to override the styling to integrate this component into an existing site's look and feel.

**Comment by piperRyan** [comment]
Ahh I see. Clearly, the issue is me. Thank you for taking the time to respond despite that.
