### ISSUE TITLE
What is the purpose of emiting a scroll event at the end of the scrolls sync method?

### ISSUE THREAD

**Issue by danielgolden** [richardtallent/vue-scrolling-table#12]
https://github.com/richardtallent/vue-scrolling-table/blob/53d98f6b524f5d19c6a7bf0d76ebbb2babfc6b1f/src/VueScrollingTable.vue#L76

**Comment by richardtallent** [comment]
This is purely for the convenience of the calling application, in case there is something the app needs to do when scrolling occurs.

I'm not sure I had a strong vision in my head of what someone might do when the table is scrolled. I've never used it. Unless someone has a strong use case for it, it could probably be removed in the next version. I'll keep this open as a potential enhancement and see if anyone else has any strong opinions on removing it.

I've been experimenting with `IntersectionObserver` in other components, now that iOS Safari will support it in the next version. Rather than a scroll event, it may make more sense for this component to just add support to allow those observers. This component wouldn't be responsible for the observer itself, since it defers table row rendering to the parent, but I think it would need to pass back a reference to the `tbody` element so the caller can set up the observer.

**Comment by danielgolden** [comment]
> This is purely for the convenience of the calling application, in case there is something the app needs to do when scrolling occurs.

Ah, ok that makes a lot of sense. Thanks for the insight. I was just trying to make sure I understood how you were accomplishing scroll sync between the two table sections and I was unsure about this emit. I don't have a strong opinion about whether the emitted scroll event is helpful (I'm not using it, but others may find it useful 🤷‍♂️).

> I've been experimenting with IntersectionObserver in other components, now that iOS Safari will support it in the next version

That's exciting, and I think it could be pretty cool. I'm not super familiar with `IntersectionObserver` but from the brief dabbling I did a bit ago it sounds like this may be an ideal application of it.
