### ISSUE TITLE
Can you migrate a sample into this repository?

### ISSUE THREAD

**Issue by kimulaco** [richardtallent/vue-scrolling-table#15]
Now, demo is divided into two different repositories.
So I think there are some disadvantages when developing features.

- Package versions are different in demo and release.
- Inefficient because verification and development are separate repositories.

**Comment by kimulaco** [comment]
I would like to consider including this sample in this repository.
https://github.com/richardtallent/vue-scrolling-table-sample

**Comment by richardtallent** [comment]
Hi @kimulaco,

I could have them in the same repo, but this wouldn't solve the problems you describe. In a combined repo, each would still be required to have their own folder structure, `package.json`, webpack and Vue configuration, etc.

I would love for Vue to have a Project Template for a Vue component (or set of components) *with* an accompanying example app, but there's not a canonical way to do this.

I have run across the same issue in my other components. I do try to keep the sample apps and components aligned in version numbers, but I do forget to bump the sample apps sometimes.

When I'm working on one of the components, I clone both repos into "sibling" folders and import them separately into Vue UI. I switch the `import` statement for the sample app to use the component in the relative sibling folder rather than the online npm version. This allows my component changes to hot-reload in the sample app. When I'm done, I switch back to referring to the component as loaded through the dependencies. This also allows me to confirm that the new version has been published on npm correctly.

You can see this in the sample app here:

https://github.com/richardtallent/vue-scrolling-table-sample/blob/master/src/App.vue#L83

It's not a perfect solution. For example, if my eslint or prettier preferences aren't identical, I end up with the code throwing linter warnings or getting reformatted. When Vue UI provides a better solution for component and library authors to include an example app, I'll probably be the first to switch!

**Comment by kimulaco** [comment]
Thank you for answer!
I understand your idea!

This is an example, but using Vue CLI v3.x seems to be somewhat easier.
https://cli.vuejs.org/guide/build-targets.html
