### ISSUE TITLE
Preserving a Fixed Table Height when filtering VueScrollingTable

### ISSUE THREAD

**Issue by MarcDBoss** [richardtallent/vue-scrolling-table#4]
Hey there,

I'm using your VueScrollingTable on a project to list tenants in a building. I've since implemented a filtering component to only show tenants that starts with the same character as the selected filter. As expected, displaying less rows within the table shrinks it to fit only the rendered rows.

![image](https://user-images.githubusercontent.com/8225247/37113696-182649c6-2214-11e8-9942-d6f581034ac4.png)
![image](https://user-images.githubusercontent.com/8225247/37113703-1d79cbc8-2214-11e8-9b85-bd7e799f49c2.png)

Is there any way to give the VueScrollingTable a fixed/min-height and force it to maintain that height regardless of the number of components (i.e. if the filter returns an empty result, it should say something like "Sorry nothing to show yet...", if there are more then scroll)?

**Comment by richardtallent** [comment]
That looks great!

The `vue-scrolling-table` component is flexbox-based and will take the height of its parent container, scrolling its contents if that parent's height is exceeded. So, all you need is to ensure that the parent element of the component either has a height based on its own flexbox attributes (if you're using flexbox), or that it has a `min-height` (to expand the component to fill the void) and a `height` (to set a maximum height so the component scrolls the body as needed). Those two values can be the same if you want the table to always be the same height. You can see an example of this in the sample application, lines 1560-1561 (`div.box` is the parent in the sample app):

https://github.com/richardtallent/vue-scrolling-table-sample/blob/master/src/App.vue

When you do this, any unused space between the bottom of your data rows and the bottom of the table is filled in with the color you specify in the "dead-area-color" attribute.

As for the "no results" message, there's nothing in the component specifically for this (since it isn't responsible for your TR/TD rendering), but it's easy enough to do this using normal Vue semantics. You just need to create a placeholder row with a message when there are no search results. Something like this would work:

```
<vue-scrolling-table>
  ...
  <template slot="tbody">
	<tr v-if="filteredItems.length==0">
		<td :colspan="columns.length" class="nothingFoundMessage">
			Sorry, nothing to show yet...
		</td>
	</tr>
	<tr v-for="item in filteredItems" :key="item.id">
		<td v-for="col in columns" :key="col.id">{{ item[col.id] }}</td>
	</tr>
  </template>
  ...
</vue-scrolling-table>
...
td.nothingFoundMessage {
	padding: 3em;
	font-weight: bold;
}
```

Hope that helps!

I'm planning to create a little gallery of people using this component, so if the site you're working on becomes publicly-accessible, please let me know!

**Comment by MarcDBoss** [comment]
Hey Richard,

Thanks for the speedy reply, you details helped me solve the issue perfectly! Now I'm able to set a constant size regardless of which tab I'm viewing and regardless of the number of table entries.

In regards to using our project in a gallery, would it be simply an image of the page? 
If that's that case I can clear it with our marketing team to make sure there aren't any issues and get back to you!
