### ISSUE TITLE
Remove deadzone when overflow is overlay

### ISSUE THREAD

**Issue by gjuchault** [richardtallent/vue-scrolling-table#6]
Hi,

If the size of the tbody is not big enough to cover all page, there is still this invisible scrollbar taking some place.
`overflow: auto` should make it hidden, and I also tried `overflow: overlay`, but this deadzone is not disappearing. Do you have an idea ?

![image](https://user-images.githubusercontent.com/678848/40476465-605ae9c8-5f44-11e8-9e05-60cf5f6cf841.png)

**Comment by gjuchault** [comment]
About the screen shot, we can clearly see the tbody and horizontal scrollbar stopping 6px before the application border (the black is desktop background)

**Comment by richardtallent** [comment]
Without seeing your code, I'm not sure what the issue is, but I can tell you that the *parent* of this Vue control should have `overflow:hidden`.

Within the component, I haven't been using `overflow:overlay` so far because it's not supported by IE11, but I'm open to doing so, provided there's a working fallback for IE11. Using `overflow:auto` doesn't work correctly -- the `tbody` and `thead` need to have the same guaranteed width to scroll in unison, and `overflow:auto` on `tbody` would result in the tbody sometimes having a scrollbar, sometimes not, which would cause a mismatch in the DOM width between it and the `thead`. (That's why the `thead` has a forced "dead area" scroll bar as well, even though it has no vertical scrolling.)
