### ISSUE TITLE
Is there a way to use this without building it with webpack?

### ISSUE THREAD

**Issue by langdonx** [richardtallent/vue-scrolling-table#7]
The minified file exposes `window.VueScrollingTable`, so I tried including it as a script tag and then doing:

    new Vue({
        ...
        components: {
            ...
            "vue-scrolling-table": window.VueScrollingTable,
        },
    ....

But it still throws `Unknown custom element: <vue-scrolling-table> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

And when I tried to use it in my component's `components` property, it says `Failed to mount component: template or render function not defined.`

**Comment by richardtallent** [comment]
Hi!

Unfortunately, I have no experience trying to use Vue components without a webpack-based build process. When I switched from RiotJS to Vue, I made the decision to go ahead and switch my build process to webpack, so I could take full advantage of the "usual" way of working with Vue, and especially because it makes it easier to work with Single File Components (which were one of the big draws for me over React, etc.). It was a bit of a transition, but I haven't regretted it. (One of my larger legacy apps still uses gulp as well, with webpack called from gulp as a task.)

But if memory serves, in the code examples I've seen, I don't recall anyone using a `window.*` reference like that in the Vue constructor. I'm probably wrong, but My guess is that you'd need to call `Vue.component()` first to register the custom element, *then* call `new Vue()` to bootstrap your application.

Also, keep in mind that the minified version is *not* compiled with polyfills, so you'll need to add those polyfills yourself if you need to support older browsers.

**Comment by langdonx** [comment]
Thanks for the input.

After a few adjustments and upon further analysis it seems that `vue-scrolling-table` (as is) cannot be used without a compilation step because of how Vue treats templates.

https://github.com/vuejs/vue/issues/2283

The template, as it's written gets translated by Vue (really, by the browser) as `<slot/><table/>` instead of `<table><slot/></table>`.  As mentioned in the issue, `is` can get around this.  I changed the template and now it's working for me:

`<table...` => `<div is="table"...`
`<thead...` => `<div is="thead"...`
`<tbody...` => `<div is="tbody"...`
`<tfoot...` => `<div is="tfoot"...`

**Comment by richardtallent** [comment]
Ah, yes! I've seen that weird table-child-moving behavior before, not specifically with `<slot/>`, but with other in-browser-compiled templates.

Rather than using `<div is...`, could you check to see if `<slot is="tr">` works? All three slots are where you'd usually find `<tr>` elements. As long as Vue ignores the `is` attribute, that would be less disruptive to the template, and would be something I'd be happy to add to the codebase, since it wouldn't have any impact on anyone using webpack.

**Comment by langdonx** [comment]
That sadly won't work because `table` is the problem.  Everything gets hoisted outside of it.

```
var a = document.createElement('div')
a.innerHTML = '<table><slot></slot></table>';
console.log(a.innerHTML);
```

**Comment by richardtallent** [comment]
Ah! I thought you were using the distribution version, which should not exhibit this issue because it has already been compiled by Vue into a render function. The only situation where you should see hoisting is if you're copying and pasting the template directly into your HTML app markup.

I played around with a plain HTML file and was able to get things working without webpack. Here's the (abbreviated) version:

```HTML
<html><head>
	<script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js"></script>
	<script src="node_modules/vue-scrolling-table/dist/vue-scrolling-table.min.js"></script>
</head><body>
<div id="app"><div class="bigBoxForTable">
	<vue-scrolling-table>[...template slots go here...]</vue-scrolling-table>
</div></div>
<script>
	VueScrollingTable.default.install(Vue)

	new Vue({
...config goes here...
	}).$mount("#app");
</script>
</body></html>
```

I suspect this wasn't the intended way of calling the install function, but it works, and and there's no need to include a `components` key in your Vue constructor argument.

You'll of course want to copy `vue-scrolling-table.min.js` out of the `node_modules` folder into somewhere in your publish folder and reference it there.

**Comment by langdonx** [comment]
Sorry to not be completely clear, I was trying a bunch of different approaches.  Mostly I was trying to use [http-vue-loader](https://github.com/FranckFreiburger/http-vue-loader) on the `.vue` file itself, which I guess does some silly stuff with the template.  I know compiling, as you mentioned, is the right way to go, but for quick proofs of concept and JSFiddles/Plnkr/etc, having this capability is quite helpful.  Thanks for all your help!
